#
#name: Notify Telegram on Push
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  notify:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Send notification to Telegram
#        uses: EverythingSuckz/github-telegram-notify@main
#        with:
#          bot_token: ${{ secrets.TELEGRAM_TOKEN }}
#          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
#          message: |
#            Nuova commit di: ${{ github.actor }}:
#            Aggiornamento: ${{ github.event.head_commit.message }}
#            Apri: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
#
